### ISSUE TITLE
Members of group ifip

### ISSUE THREAD

**Issue by ahocevar** [tuwien-geoweb-2015/ifip-block3#1]
@ahocevar, please add us as members:

**Comment by CBraque** [comment]
group 3:
@CBraque
@cniessner
@FlorianEhrenreich

**Comment by balcse** [comment]
group 5:
@balcse
@sonjal
@ngocd

**Comment by ghost** [comment]
@ahocevar , bitte Gruppe 1 hinzufügen:

@Buglkrax
@AnnaLogar
@Griesstina

**Comment by agnesdaniel** [comment]
group 7:
@agnesdaniel
@fkeringer
@linkras

**Comment by IsoldeP** [comment]
@ahocevar, please add us as members. username: @IsoldeP @guntherbuffet
thanks, group 06!

**Comment by buqq** [comment]
Gruppe 9:

@buqq
@MoritzStarzer
@WeberChristoph

**Comment by ahocevar** [comment]
Thanke everyone, welcome!
