### ISSUE TITLE
Gruppe 8

### ISSUE THREAD

**Issue by vanperste** [tuwien-geoweb-2015/ifip-block3#6]
@ahocevar 
Gruppe 8:
@vanperste
(der Gruppenparter wird sich nachträglich melden)

**Comment by ahocevar** [comment]
Welcome! I'm leaving this open so your partner can mention their name here.

**Comment by Hoebi** [comment]
@ahocevar 
Please add me to Group 8
@hoebi

**Comment by ahocevar** [comment]
Welcome @Hoebi.
